#!/usr/bin/env python3
"""Stitch chunk .pas files into per-variant scripts.

Variants: SINGLE, MULTI, DEBUG.

Directives are line-oriented -- each marker must be on its own line:

    {#IF VAR1[,VAR2,...]}     include block when current variant is in the list
    {#IF NOT VAR}             include block when current variant is NOT VAR
    {#ELSEIF VAR}             chained alternative
    {#ELSE}                   fallthrough alternative
    {#ENDIF}                  close block

Nesting is supported. Markers themselves are stripped from output.
Lines outside any IF block are always emitted. Lines inside an inactive
branch are dropped.

Usage:
    python build.py SINGLE          -> WryeBashTagGenerator-NG.pas
    python build.py MULTI           -> WryeBashTagGenerator-Multi-NG.pas
    python build.py DEBUG           -> WryeBashTagGenerator-NG-debug.pas
    python build.py all             -> all three
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).parent
CHUNK_DIR = ROOT / "chunks"

OUT = {
    "SINGLE": "WryeBashTagGenerator-NG.pas",
    "MULTI":  "WryeBashTagGenerator-Multi-NG.pas",
    "DEBUG":  "WryeBashTagGenerator-NG-debug.pas",
}
VARIANTS = set(OUT)

# Match a directive on its own line. Allow leading/trailing whitespace.
DIRECTIVE_RE = re.compile(r'^\s*\{#(IF|ELSEIF|ELSE|ENDIF)(?:\s+(.+?))?\s*\}\s*$')

GENERATED_MARKER = "{ GENERATED FROM chunks/ by build.py"
GENERATED_BANNER = (
    GENERATED_MARKER + " -- DO NOT EDIT THIS FILE DIRECTLY.\n"
    "  Edit the corresponding chunk in chunks/ and re-run: python build.py all\n"
    "  Variant: %s }\n"
)


def parse_cond(arg: str, variant: str) -> bool:
    """Evaluate an IF/ELSEIF condition against the active variant."""
    arg = (arg or "").strip()
    if not arg:
        raise SyntaxError("IF/ELSEIF requires at least one variant")
    negate = False
    upper = arg.upper()
    if upper.startswith("NOT "):
        negate = True
        arg = arg[4:].strip()
    parts = {p.strip().upper() for p in arg.split(",") if p.strip()}
    unknown = parts - VARIANTS
    if unknown:
        raise SyntaxError(f"unknown variant(s) in directive: {sorted(unknown)}")
    matched = variant in parts
    return matched ^ negate


def process(text: str, variant: str, src: str) -> str:
    """Apply directives in `text` for the given variant. Returns processed text."""
    out = []
    # Stack entries: (active_now, taken_already)
    #   active_now    -- emit lines while in this branch?
    #   taken_already -- has any branch in this IF chain been taken yet?
    stack = []

    for lineno, line in enumerate(text.splitlines(keepends=True), 1):
        m = DIRECTIVE_RE.match(line)
        if not m:
            if all(s[0] for s in stack):
                out.append(line)
            continue

        kind = m.group(1).upper()
        arg = m.group(2)

        if kind == "IF":
            parent_active = all(s[0] for s in stack)
            cond = parse_cond(arg, variant)
            stack.append((parent_active and cond, cond))

        elif kind == "ELSEIF":
            if not stack:
                raise SyntaxError(f"{src}:{lineno}: ELSEIF without IF")
            _, taken = stack[-1]
            parent_active = all(s[0] for s in stack[:-1])
            cond = (not taken) and parse_cond(arg, variant)
            stack[-1] = (parent_active and cond, taken or cond)

        elif kind == "ELSE":
            if arg:
                raise SyntaxError(f"{src}:{lineno}: ELSE takes no argument")
            if not stack:
                raise SyntaxError(f"{src}:{lineno}: ELSE without IF")
            _, taken = stack[-1]
            parent_active = all(s[0] for s in stack[:-1])
            stack[-1] = (parent_active and not taken, True)

        elif kind == "ENDIF":
            if arg:
                raise SyntaxError(f"{src}:{lineno}: ENDIF takes no argument")
            if not stack:
                raise SyntaxError(f"{src}:{lineno}: ENDIF without IF")
            stack.pop()

    if stack:
        raise SyntaxError(f"{src}: unclosed IF block ({len(stack)} open)")

    return "".join(out)


def build(variant: str) -> pathlib.Path:
    if not CHUNK_DIR.is_dir():
        sys.exit(f"chunk dir not found: {CHUNK_DIR}")
    chunks = sorted(CHUNK_DIR.glob("*.pas"))
    if not chunks:
        sys.exit(f"no .pas chunks found in {CHUNK_DIR}")

    parts = [GENERATED_BANNER % variant]
    for chunk in chunks:
        text = chunk.read_text(encoding="utf-8")
        processed = process(text, variant, chunk.name)
        # Guarantee a chunk boundary newline -- splitlines(keepends=True)
        # preserves the absence of a trailing newline, which would otherwise
        # glue the next chunk's first line onto the previous chunk's last.
        if processed and not processed.endswith("\n"):
            processed += "\n"
        parts.append(processed)

    out_path = ROOT / OUT[variant]
    if out_path.exists():
        head = out_path.read_text(encoding="utf-8", errors="replace")[:200]
        if GENERATED_MARKER not in head:
            sys.exit(
                f"refusing to overwrite {out_path.name}: file does not carry the\n"
                f"GENERATED banner, so it looks like a hand-edited script. Move or\n"
                f"delete it first if you really want to regenerate."
            )
    out_path.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {out_path.name}  ({out_path.stat().st_size:>7} bytes from {len(chunks)} chunks)")
    return out_path


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    target = sys.argv[1].upper()
    if target == "ALL":
        for v in OUT:
            build(v)
    elif target in OUT:
        build(target)
    else:
        sys.exit(f"unknown target: {sys.argv[1]!r}; use SINGLE / MULTI / DEBUG / all")


if __name__ == "__main__":
    main()
