{ chunk: BashTags file IO + prompts -- ReadBashTagsFile, WriteBashTagsFileWithBackup, HeaderBashTagsDiffer, PromptDeprecatedHeaderUpdate, PromptApproveBashTagsBackup, NotifyHeaderBashTagsDiscrepancy }

Function PromptDeprecatedHeaderUpdate: boolean;
Begin
  Result := MessageDlg(
    'This plugin description contains deprecated Bash Tags (obsolete names Wrye Bash no longer uses).'#13#10 +
    'Update the {{BASH:...}} block to modern tag names when writing the header?',
    mtConfirmation, [mbYes, mbNo], 0) = mrYes;
End;

{#IF SINGLE,MULTI}
// Reads Data\BashTags\<plugin>.txt (Wrye Bash format) into:
//   slBashTagsFileAdds    - bare tags (canonical, normalized)
//   slBashTagsFileRemoves - tag names that were prefixed with '-' in the file
//   slBashTagsFileLines   - raw original lines, preserved for in-place backup
// '#' starts a comment to end of line; tags are comma-separated and may span lines.
Procedure ReadBashTagsFile(Const APath: string);

Var 
  i, k     : integer;
  iHash    : integer;
  sLine    : string;
  sEntry   : string;
  slParts  : TStringList;
Begin
  slBashTagsFileAdds.Clear;
  slBashTagsFileRemoves.Clear;
  slBashTagsFileLines.Clear;
  g_BashTagsFileExists := FileExists(APath);
  If Not g_BashTagsFileExists Then Exit;

  slBashTagsFileLines.LoadFromFile(APath);

  slParts := TStringList.Create;
  Try
    slParts.StrictDelimiter := True;
    slParts.Delimiter       := ',';
    For i := 0 To Pred(slBashTagsFileLines.Count) Do
      Begin
        sLine := slBashTagsFileLines[i];
        iHash := Pos('#', sLine);
        If iHash > 0 Then
          sLine := Copy(sLine, 1, iHash - 1);
        sLine := Trim(sLine);
        If sLine = '' Then Continue;
        slParts.DelimitedText := sLine;
        For k := 0 To Pred(slParts.Count) Do
          Begin
            sEntry := Trim(slParts[k]);
            If sEntry = '' Then Continue;
            If sEntry[1] = '-' Then
              slBashTagsFileRemoves.Add(Trim(Copy(sEntry, 2, Length(sEntry) - 1)))
            Else
              slBashTagsFileAdds.Add(sEntry);
          End;
      End;
  Finally
    slParts.Free;
  End;

  NormalizeBashTagsInPlace(slBashTagsFileAdds);
  NormalizeBashTagsInPlace(slBashTagsFileRemoves);
End;


// Writes APath as a Wrye-Bash-readable BashTags file:
//   - '# Generated by ScriptName vScriptVersion'
//   - if ABackup and AOriginalLines is non-empty, the original contents are
//     preserved as commented lines wrapped in begin/end markers
//   - one comma-separated tag line containing ANewLine
Procedure WriteBashTagsFileWithBackup(Const APath: string;
                                      Const ANewLine: string;
                                      Const AOriginalLines: TStringList;
                                      ABackup: boolean);

Var 
  slOut : TStringList;
  i     : integer;
Begin
  ForceDirectories(ExtractFilePath(APath));
  slOut := TStringList.Create;
  Try
    slOut.Add('# Generated by ' + ScriptName + ' v' + ScriptVersion);
    If ABackup And (AOriginalLines.Count > 0) Then
      Begin
        slOut.Add('# --- Backup of previous file contents (' + DateTimeToStr(Now) + ') ---');
        For i := 0 To Pred(AOriginalLines.Count) Do
          slOut.Add('# ' + AOriginalLines[i]);
        slOut.Add('# --- End backup ---');
      End;
    slOut.Add(ANewLine);
    slOut.SaveToFile(APath);
  Finally
    slOut.Free;
  End;
End;


// True iff the normalized tag set in the {{BASH:...}} header block differs
// from the additive set in the existing BashTags file.
Function HeaderBashTagsDiffer: boolean;

Var 
  slA : TStringList;
  slB : TStringList;
Begin
  slA := MakeTagSet;
  slB := MakeTagSet;
  Try
    slA.AddStrings(slExistingTags);
    slB.AddStrings(slBashTagsFileAdds);
    NormalizeBashTagsInPlace(slA);
    NormalizeBashTagsInPlace(slB);
    Result := Not TagsCommaTextEqual(slA, slB);
  Finally
    slA.Free;
    slB.Free;
  End;
End;


// Show the header/BashTags discrepancy warning with Skip/Abort buttons.
// Returns True if the user chose Abort (halt the entire run);
// returns False if the user chose Ignore (skip writes for this plugin, continue).
// Writes are suppressed for the current plugin either way — the result only
// decides whether subsequent plugins are processed.
Function NotifyHeaderBashTagsDiscrepancy: boolean;

Var
  iResult : integer;
Begin
{#IF MULTI}
  // Multi mode: always ignore discrepancy and continue (matching the older
  // multifile behavior). Still warn loudly so the user can correct it.
    LogWarn('Header/BashTags discrepancy detected; skipping writes for this plugin and continuing.');
  Result := False;
{#ELSEIF SINGLE}
  iResult := MessageDlg(
    'The {{BASH:...}} block in the plugin header and the existing BashTags '
    + 'file disagree on tags for plugin:'#13#10
    + '    ' + g_FileName + #13#10#13#10
    + 'This script does not reconcile the two; please fix the discrepancy '
    + 'manually.'#13#10#13#10
    + 'Ignore = skip writes for this plugin, continue with the next.'#13#10
    + 'Abort  = halt the run; no further plugins will be processed.',
    mtWarning, [mbIgnore, mbAbort], 0);
  Result := (iResult = mrAbort);
{#ENDIF}
End;


Function PromptApproveBashTagsBackup: boolean;
Begin
  Result := MessageDlg(
    'About to back up the existing BashTags file in-place (the original lines will '
    + 'be commented out at the top of the file) and overwrite it with the new tag '
    + 'list:'#13#10 + g_BashTagsFilePath + #13#10#13#10
    + 'Approve?  (No = discard the change, leave the existing file intact, terminate normally.)',
    mtConfirmation, [mbYes, mbNo], 0) = mrYes;
End;
{#ENDIF}
