# Wrye Bash Tags Reference

Distilled from https://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#patch-list-of-tags (fetched 2026-04-21).

Consult when adding or modifying a tag branch in `ProcessTag`, or when updating the alias/removal maps in `ExpandOneAliasTo` / `TagIsRemoved`. Game applicability notes come straight from the upstream tables — if a tag isn't listed for a game here, it doesn't apply there.

Upstream source files in Wrye Bash: `Mopy/bash/bosh/__init__.py` (`_tag_aliases`, `_removed_tags`).

### Local augmentation: Detection lines

Some tag entries carry a third bullet — `**Detection (this script):**` — summarizing how `WryeBashTagGenerator-NG.pas` actually decides to emit the tag. These lines are **not** from upstream. They're here because the upstream docs describe a tag's *meaning* to the Bashed Patch, not the precise override-vs-master diff this script performs. The annotations cover the non-obvious cases only: specialty procedures (`ProcessRaceSpells`, `ProcessDelevRelevTags`, `ProcessForceTagHeuristics`), `DiffSubrecordList`-driven `.Change` tags (which intentionally ignore pure adds/removes), `Actors.Factions` gating, per-game path differences (RACE SPLO is `'Spells'` on Oblivion vs `'Actor Effects'` on Skyrim+), and the opt-in Force-add heuristics. For tags without a Detection bullet, the rule is the obvious one: the override differs from the master on the subrecord listed in **Records**.

**If this file is ever regenerated by re-fetching upstream and re-distilling, redo this Detection pass.** The source of truth for each Detection line is the corresponding branch in `ProcessTag` or the specialty procedure it delegates to — grep the script for the tag name to find it.

## Special function tags

These aren't game-specific and have no record-diffing semantics — they're hints to the Bashed Patch process. This script generally should **not** emit these itself; they're for authors to set manually.

| Tag | Meaning |
|---|---|
| Deactivate | Plugin should be deactivated. |
| Filter | Plugin doesn't require all masters to function. See Filtering section. |
| IIM | Use in Item Interchange Mode. |
| MustBeActiveIfImported | Must be active even when imported into the Bashed Patch (suppresses the deactivation prompt). |
| NoMerge | Do not merge even though it's technically mergeable. |

## Removed & deprecated tags → replacements

This is the authoritative alias/removal map. Mirror changes into `ExpandOneAliasTo` / `TagIsRemoved` in the script.

| Old tag | Replacement / notes |
|---|---|
| Actors.Perks.Add | → NPC.Perks.Add |
| Actors.Perks.Change | → NPC.Perks.Change |
| Actors.Perks.Remove | → NPC.Perks.Remove |
| Body-F | → R.Body-F |
| Body-M | → R.Body-M |
| Body-Size-F | → R.Body-Size-F |
| Body-Size-M | → R.Body-Size-M |
| C.GridFlags | → C.ForceHideLand |
| Derel | → Relations.Remove |
| Eyes | → R.Eyes |
| Eyes-D | → R.Eyes |
| Eyes-E | → R.Eyes |
| Eyes-R | → R.Eyes |
| Factions | → Actors.Factions |
| Hair | → R.Hair |
| Invent | → split into Invent.Add, Invent.Change, Invent.Remove. Old behavior = Invent.Add + Invent.Remove. |
| InventOnly | → use Invent.* tags in conjunction with IIM. |
| Merge | Removed — obsoleted by Merge Patches rework. |
| Npc.EyesOnly | → NPC.Eyes |
| Npc.HairOnly | → NPC.Hair |
| NpcFaces | → split into NPC.Eyes, NPC.Hair, NPC.FaceGen. Old behavior = all three combined. |
| R.Relations | → split into R.Relations.Add, R.Relations.Change, R.Relations.Remove. Old = all three. |
| Relations | → split into Relations.Add and Relations.Change. Old behavior = Relations.Add + Relations.Change. |
| ScriptContents | Removed — dangerous tag that was never fully implemented. |
| Voice-F | → R.Voice-F |
| Voice-M | → R.Voice-M |

## Shared across games

Tags in this section exist for multiple games; per-game specifics (exact subrecords) live in the per-game sections below.

### Actors.ACBS
- **When:** Modifies the (ACBS) Configuration subrecord of actors.
- **Records:** Game-specific; see per-game Actors.ACBS sections for NPC_ / CREA fields.

### Actors.AIData
- **When:** Modifies the (AIDT) AI Data subrecord of actors.
- **Records:** Game-specific; see per-game Actors.AIData sections (NPC_, CREA).

### Actors.AIPackages
- **When:** Modifies AI package lists of actors (add or remove).
- **Records:** (PKID) AI Package in CREA (Oblivion/Nehrim/FO3/FNV only) and NPC_.

### Actors.AIPackagesForceAdd
- **When:** Force-adds AI packages even when later plugins tagged Actors.AIPackages would remove them.
- **Records:** (PKID) AI Package in CREA (Oblivion/Nehrim/FO3/FNV only) and NPC_.
- **Detection (this script):** `ProcessForceTagHeuristics`, gated on `g_HeuristicForceTags`. Fires only when `Actors.AIPackages` was already suggested AND the override's `Packages` array is a strict superset of the master's (adds at least one, removes none).

### Actors.Anims
- **When:** Modifies actor special animations lists.
- **Records:** (KFFZ) Animations in CREA and NPC_. Oblivion/Nehrim/FO3/FNV only.

### Actors.CombatStyle
- **When:** Modifies the assigned combat styles of actors.
- **Records:** (ZNAM) Combat Style in CREA (Oblivion/Nehrim/FO3/FNV only) and NPC_.

### Actors.DeathItem
- **When:** Modifies actor death items.
- **Records:** (INAM) Death Item in CREA (Oblivion/Nehrim/FO3/FNV only) and NPC_.

### Actors.Factions
- **When:** Changes creature and NPC factions (add/remove/rank change).
- **Records:** (SNAM) Faction / (SNAM) Faction-Rank in NPC_ / CREA (CREA: Oblivion/Nehrim/FO3/FNV only).
- **Detection (this script):** `CompareAssignment` + `CompareKeys` on the whole `Factions` subrecord. Fires when the faction list is assigned on one side only, or when the sorted key contents (faction FormID + rank together) differ — so rank-only changes trigger the tag.

### Actors.RecordFlags
- **When:** Modifies actor record flags.
- **Records:** Record flags in CREA (Oblivion/Nehrim/FO3/FNV only) and NPC_.

### Actors.Skeleton
- **When:** Modifies actor skeletons.
- **Records:** (MODL) Model Filename, (MODB) Bound Radius, (MODT) Texture File Hashes in NPC_ / CREA. Oblivion/Nehrim/FO3/FNV only.

### Actors.Spells
- **When:** Modifies actor spell / actor-effects lists (add/modify/remove).
- **Records:** (SPLO) Spells in CREA (Oblivion/Nehrim/FO3/FNV only) and NPC_.

### Actors.SpellsForceAdd
- **When:** Force-adds spells to actors even when other plugins tagged Actors.Spells would remove them.
- **Records:** (SPLO) Spells in CREA (Oblivion/Nehrim/FO3/FNV only) and NPC_.
- **Detection (this script):** `ProcessForceTagHeuristics`, gated on `g_HeuristicForceTags` checkbox. Fires only when `Actors.Spells` was already suggested AND the override's SPLO list is a strict superset of the master's (adds at least one, removes none). Array path is `'Spells'` on Oblivion/Nehrim, `'Actor Effects'` elsewhere.

### Actors.Stats
- **When:** Modifies actor stats (health, skills, stamina, etc.).
- **Records:** Game-specific; see per-game Actors.Stats sections.

### Actors.Voice
- **When:** Changes the voices of actors.
- **Records:** (VTCK) Voice in CREA (FO3/FNV only) and NPC_. Not for Oblivion/Nehrim.

### C.Acoustic
- **When:** Modifies cell Acoustic Space.
- **Records:** (XCAS) Acoustic Space in CELL. Not for Oblivion/Nehrim/FO4.

### C.Climate
- **When:** Modifies cell climates.
- **Records:** (XCCM) Climate + (DATA-Flags) Behave Like Exterior (Oblivion/Nehrim/FO3/FNV); (XCCM) Sky/Weather from Region + (DATA-Flags) Show Sky (Skyrim/Enderal/SSE). Not for FO4.

### C.Encounter
- **When:** Modifies cell Encounter Zone.
- **Records:** (XEZN) Encounter Zone in CELL. Not for Oblivion/Nehrim/FO4.

### C.ForceHideLand
- **When:** Modifies cell Force Hide Land flags.
- **Records:** Force Hide Land flags in Grid (XCLC) subrecord of CELL. Not for Oblivion/Nehrim/FO4.

### C.ImageSpace
- **When:** Modifies cell ImageSpace.
- **Records:** (XCIM) Image Space in CELL. Not for Oblivion/Nehrim/FO4.

### C.Light
- **When:** Modifies cell lighting or fog.
- **Records:** (XCLL) Lighting (Ambient/Directional/Fog colors, Fog Near/Far/Clip/Power, Directional Rotation XY/Z, Directional Fade); (LTMP) Light Template (not Oblivion/Nehrim); (LNAM) Light Template Inherits (FO3/FNV); Skyrim variant adds Ambient Colors Directional/Specular/Scale, Fog Color Far, Fog Max, Light Fade Begin/End, Inherits. Not for FO4.

### C.LockList
- **When:** Modifies cell lock list.
- **Records:** (XILL) Lock List in CELL. Skyrim/Enderal/SSE only.

### C.Location
- **When:** Modifies cell Location.
- **Records:** (XLCN) Location in CELL. Skyrim/Enderal/SSE only.

### C.MiscFlags
- **When:** Modifies miscellaneous CELL flags not covered by other tags.
- **Records:** (DATA) Flags: Is Interior Cell, Can't Travel From Here / Invert Fast Travel Behavior, No LOD Water (not Oblivion/Nehrim/FO4), Force Hide Land / Oblivion Interior (Oblivion/Nehrim only), Hand Changed. Not for FO4.

### C.Music
- **When:** Modifies cell music type.
- **Records:** (XCMT) Music (Oblivion/Nehrim); (XCMO) Music (all but Oblivion/Nehrim/FO4). Not for FO4.

### C.Name
- **When:** Modifies cell names.
- **Records:** (FULL) Name in CELL. Not for FO4.

### C.Owner
- **When:** Modifies cell ownership.
- **Records:** (XOWN) Owner, (XRNK) Rank, (XGLB) Global variable (Oblivion/Nehrim only), (DATA-Flags) Public Place in CELL. Not for FO4.

### C.RecordFlags
- **When:** Modifies record flags in CELL records.
- **Records:** Any CELL record flags. Not for FO4.

### C.Regions
- **When:** Modifies the Cell's Region subrecord.
- **Records:** (XCLR) Region in CELL. Not for FO4.

### C.SkyLighting
- **When:** Modifies Use Sky Lighting CELL flag.
- **Records:** (DATA-Flags) Use Sky Lighting. Skyrim/Enderal/SSE only.

### C.Water
- **When:** Modifies cell water type or level.
- **Records:** (XCWT) Water, (XCLW) Water Height, (DATA-flags) Has Water, (XNAM) Water Noise Texture (not Oblivion/Nehrim), (XWEM) Water Environment Map (Skyrim/Enderal/SSE only). Not for FO4.

### Creatures.Blood
- **When:** Modifies creature blood subrecords.
- **Records:** CREA: (NAM0) Blood Spray, (NAM1) Blood Decal (Oblivion/Nehrim only); (CNAM) Impact Dataset (FO3/FNV only).

### Creatures.Type
- **When:** Modifies the type of creatures.
- **Records:** CREA (DATA) Stats: Type. Oblivion/Nehrim: Creature/Daedra/Undead/Humanoid/Horse/Giant. FO3/FNV: Animal/Mutated Animal/Mutated Insect/Abomination/Super Mutant/Feral Ghoul/Robot/Giant.

### Deflst
- **When:** Removes entries from FormID List records.
- **Records:** (FLST) FormIDs → (LNAM) FormID removals. FO3/FNV only.

### Delev
- **When:** Deletes entries from Leveled Lists.
- **Records:** Removal of (LVLO) Level List Entry in LVLC (Oblivion/Nehrim/FO3/FNV only), LVLI, LVLN (not Oblivion/Nehrim), LVSP (not FO3/FNV).
- **Detection (this script):** `ProcessDelevRelevTags`. For each override LVLO entry, looks up the master entry by `LVLO\Reference`; counts matches. Fires if fewer override entries match than the master has total — i.e., master entries are missing from override. Signature gating: LVLC (Oblivion/Nehrim/FO3/FNV), LVLI (all), LVLN (not Oblivion/Nehrim), LVSP (Oblivion/Skyrim/FO4).

### Destructible
- **When:** Modifies destructible records.
- **Records:** Game-specific; see per-game Destructible sections.

### EffectStats
- **When:** Modifies (MGEF) Magic Effect / Base Effect stats.
- **Records:** MGEF (DATA) fields. Pre-Skyrim: Flags, Base Cost, Associated Item, Magic School, Resist Value, Projectile Speed, Constant Effect Enchantment Factor, Constant Effect Barter Factor, Archetype (FO3/FNV), Actor Value (FO3/FNV). Skyrim+: Flags, Base Cost, Associated Item, Magic Skill (not FO4), Resist Value, Taper Weight, Minimum Skill Level, Spellmaking (Area, Casting Time), Taper Curve, Taper Duration, Second AV Weight, Archetype, Actor Value, Casting Type, Delivery, Second Actor Value, Skill Usage Multiplier, Equip Ability, Perk to Apply, Script Effect AI (Score, Delay Time).

### Enchantments
- **When:** Modifies enchantments / object effects applied to objects.
- **Records:** Oblivion/Nehrim: AMMO/ARMO/BOOK/CLOT/WEAP (ENAM). FO3/FNV: ARMO/EXPL/WEAP (EITM), CREA/NPC_ (EITM) Unarmed Attack Effect. Skyrim/Enderal/SSE: ARMO/EXPL/WEAP (EITM). FO4: ARMO/EXPL (EITM).

### EnchantmentStats
- **When:** Modifies (ENCH) Enchantment / Object Effect stats.
- **Records:** ENCH (ENIT) Effect Data. Pre-Skyrim: Type, Charge Amount, Enchant Cost, Flags. Skyrim+: Enchantment Cost, Flags, Cast Type, Enchantment Amount, Target Type, Enchant Type, Charge Time, Base Enchantment, Worn Restrictions.

### Graphics
- **When:** Is a graphics replacer.
- **Records:** Game-specific; see per-game Graphics sections. Not for FO4.

### Invent.Add
- **When:** Adds items to inventories.
- **Records:** Items in COBJ (Skyrim+), CONT, CREA (Oblivion/Nehrim/FO3/FNV), FURN (FO4), NPC_. Note: FormID change = Invent.Add + Invent.Remove.

### Invent.Change
- **When:** Changes other properties (count, owner) of inventory items.
- **Records:** Items in COBJ (Skyrim+), CONT, CREA (Oblivion/Nehrim/FO3/FNV), FURN (FO4), NPC_.
- **Detection (this script):** `DiffSubrecordList` on `Items`, key=`CNTO\Item`, data paths=`CNTO\Count` (Oblivion/Nehrim) or `CNTO\Count|COED` (all other games). Fires only for items present in BOTH master and override whose count (or extra data, on non-Oblivion) differs. Items only in override go to Invent.Add; items only in master go to Invent.Remove — never here.

### Invent.Remove
- **When:** Removes items from inventories.
- **Records:** Items in COBJ (Skyrim+), CONT, CREA (Oblivion/Nehrim/FO3/FNV), FURN (FO4), NPC_.

### Keywords
- **When:** Modifies the lists of keywords attached to things.
- **Records:** Game-specific; see Skyrim / FO4 Keywords sections.

### Names
- **When:** Changes the names of things.
- **Records:** Game-specific; see per-game Names sections.

### NPC.AIPackageOverrides
- **When:** Changes NPC package override lists.
- **Records:** NPC_ (SPOR) Spectator, (OCOR) Observe Dead Body, (GWOR) Guard Warn, (ECOR) Combat Override. Skyrim+.

### NPC.AttackRace
- **When:** Changes the attack race of NPCs.
- **Records:** (ATKR) Attack Race in NPC_. Skyrim+.

### NPC.Class
- **When:** Changes the classes of NPCs.
- **Records:** (CNAM) Class in NPC_.

### NPC.CrimeFaction
- **When:** Changes the crime factions of NPCs.
- **Records:** (CRIF) Crime Faction in NPC_. Skyrim+.

### NPC.DefaultOutfit
- **When:** Changes the default outfits of NPCs.
- **Records:** (DOFT) Default Outfit in NPC_. Skyrim+.

### NPC.Eyes
- **When:** Modifies NPC eyes.
- **Records:** (ENAM) Eyes in NPC_. Oblivion/Nehrim/FO3/FNV only.

### NPC.FaceGen
- **When:** Modifies NPC faces.
- **Records:** NPC_ (FGGS) FaceGen Geometry-Symmetric, (FGGA) FaceGen Geometry-Asymmetric, (FGTS) FaceGen Texture-Symmetry. Oblivion/Nehrim/FO3/FNV only.

### NPC.Hair
- **When:** Modifies NPC hair.
- **Records:** NPC_ (HNAM) Hair, (LNAM) Hair length, (HCLR) Hair color. Oblivion/Nehrim/FO3/FNV only.

### NPC.Perks.Add
- **When:** Adds new perks to NPCs.
- **Records:** (PRKR) Perk additions in NPC_. Skyrim+.

### NPC.Perks.Change
- **When:** Changes the rank of NPC perks.
- **Records:** (PRKR) Perk rank changes in NPC_. Skyrim+.
- **Detection (this script):** `DiffSubrecordList` on `Perks`, key=`Perk`, data=`Rank`. Fires only for perks present in BOTH master and override with differing rank. New perks → NPC.Perks.Add; removed perks → NPC.Perks.Remove.

### NPC.Perks.Remove
- **When:** Removes perks from NPCs.
- **Records:** (PRKR) Perk removals in NPC_. Skyrim+.

### NPC.Race
- **When:** Changes the races of NPCs.
- **Records:** (RNAM) Race in NPC_.

### NpcFacesForceFullImport
- **When:** Force-imports unmodified NPC face subrecords alongside modified ones (replaces NPC.Eyes/NPC.FaceGen/NPC.Hair).
- **Records:** NPC_ FaceGen Data (FGGS/FGGA/FGTS), (ENAM) Eyes, (HNAM) Hair, (LNAM) Hair Length, (HCLR) Hair Color. Oblivion/Nehrim/FO3/FNV only.
- **Detection (this script):** `ProcessForceTagHeuristics`, gated on `g_HeuristicForceTags`, NPC_ only, not on FO4. Fires only when ALL THREE of ENAM (eyes), HNAM (hair), and FaceGen Data differ from master simultaneously — any one matching the master suppresses the tag.

### ObjectBounds
- **When:** Changes the object bounds of things.
- **Records:** Game-specific; see per-game ObjectBounds sections. Not for Oblivion/Nehrim.

### Outfits.Add
- **When:** Adds items to outfits.
- **Records:** Item additions in (OTFT) Outfit. Skyrim+.

### Outfits.Remove
- **When:** Removes items from outfits.
- **Records:** Item removals in (OTFT) Outfit. Skyrim+.

### R.AddSpells
- **When:** Adds spells to racial spell list(s). Use either R.ChangeSpells or R.AddSpells, not both.
- **Records:** Spell list additions in RACE. Oblivion/Nehrim/Skyrim/Enderal/SSE only.
- **Detection (this script):** `ProcessRaceSpells`. Fires when the override RACE SPLO list adds at least one SPEL vs master AND removes none. Mutually exclusive with R.ChangeSpells (any removal flips the tag to R.ChangeSpells). Array path is `'Spells'` on Oblivion/Nehrim, `'Actor Effects'` on Skyrim/Enderal/SSE.

### R.Body-F / R.Body-M
- **When:** Modifies female / male body mesh/texture definitions in RACE.
- **Records:** RACE Female/Male Body Data: Model, Parts. Oblivion/Nehrim/FO3/FNV only.

### R.Body-Size-F / R.Body-Size-M
- **When:** Modifies female / male body weight/height in RACE.
- **Records:** RACE (DATA) Female/Male Height, Weight. Oblivion/Nehrim/FO3/FNV only.

### R.ChangeSpells
- **When:** Modifies racial spell lists beyond adding spells. Use either R.ChangeSpells or R.AddSpells, not both.
- **Records:** Additions/removals in (SPLO) spell list of RACE. Oblivion/Nehrim/Skyrim/Enderal/SSE only.
- **Detection (this script):** `ProcessRaceSpells`. Fires whenever the override removes at least one SPEL from the master's RACE SPLO list (regardless of whether it also adds). Takes precedence over R.AddSpells. Same per-game path as R.AddSpells.

### R.Description
- **When:** Modifies race descriptions.
- **Records:** (DESC) Description in RACE. All games but FO4.

### R.Ears
- **When:** Modifies race ears.
- **Records:** RACE Face Data Part: Ear (Male/Female) — (MODL), (MODB), (ICON). Oblivion/Nehrim/FO3/FNV only.

### R.Eyes
- **When:** Adds eyes to races.
- **Records:** Game-specific; see Oblivion/FO3 R.Eyes. Oblivion/Nehrim/FO3/FNV only.

### R.Hair
- **When:** Adds hairs to races.
- **Records:** (HNAM) Hairs in RACE. Oblivion/Nehrim/FO3/FNV only.

### R.Head
- **When:** Modifies race heads.
- **Records:** Game-specific; see Oblivion/FO3 R.Head. Oblivion/Nehrim/FO3/FNV only.

### R.Mouth
- **When:** Modifies race mouths.
- **Records:** Game-specific; see Oblivion/FO3 R.Mouth. Oblivion/Nehrim/FO3/FNV only.

### R.Relations.Add / R.Relations.Change / R.Relations.Remove
- **When:** Adds / changes / removes race-faction relationships.
- **Records:** (XNAM) faction list of RACE. Oblivion/Nehrim/FO3/FNV only.
- **Detection for R.Relations.Change (this script):** `DiffSubrecordList` on `Relations`, key=`Faction`, data=`Modifier` (Oblivion/Nehrim) or `Modifier|Group Combat Reaction` (FO3/FNV). Same algorithm as Relations.Change but on RACE rather than FACT. Pure adds/removes go to the Add/Remove siblings.

### R.Skills
- **When:** Modifies race skill bonuses.
- **Records:** (DATA) skills and skill boosts of RACE. All games but FO4.

### R.Teeth
- **When:** Modifies race upper or lower teeth.
- **Records:** Game-specific; see Oblivion/FO3 R.Teeth. Oblivion/Nehrim/FO3/FNV only.

### R.Voice-F / R.Voice-M
- **When:** Modifies female / male voice definitions.
- **Records:** (VNAM / VTCK) female/male voice of RACE. All games but FO4.

### Relations.Add / Relations.Change / Relations.Remove
- **When:** Adds / changes / removes faction relationships.
- **Records:** (XNAM) Relation subrecord of (FACT). Change fields: Modifier, Group Combat Reaction (not Oblivion).
- **Detection for Relations.Change (this script):** `DiffSubrecordList` on `Relations`, key=`Faction`, data=`Modifier` (Oblivion/Nehrim) or `Modifier|Group Combat Reaction` (all other games). Fires only for relations present in BOTH master and override with differing data. Add/Remove siblings use the standard add/remove evaluator.

### Relev
- **When:** Re-levels leveled list entries (Level/Count changes).
- **Records:** (LVLO) leveled list entry in LVLC (Oblivion/Nehrim/FO3/FNV only), LVLI, LVLN (not Oblivion/Nehrim), LVSP (not FO3/FNV).
- **Detection (this script):** `ProcessDelevRelevTags`. For each shared entry (matched by `LVLO\Reference`), fires if `LVLO\Level` or `LVLO\Count` differs, or — on non-Oblivion/Nehrim — if the COED extra-data subrecord's edit values differ. Pure adds/removes do NOT trigger Relev; those are Delev territory.

### Scripts
- **When:** Modifies scripts attached to various things.
- **Records:** Game-specific; see Oblivion/FO3 Scripts. Oblivion/Nehrim/FO3/FNV only.

### Sound
- **When:** Replaces sounds.
- **Records:** Game-specific; see per-game Sound sections. Not for FO4.

### SpellStats
- **When:** Modifies spell stats.
- **Records:** (SPEL) and (SCRL Skyrim-only). All games but FO4: (EDID) Editor ID, (SPIT) Cost, Spell Type, Flags. Oblivion/Nehrim/FO3/FNV: (SPIT) Level. Skyrim/Enderal/SSE: (SPIT) Cast Duration, Cast Type, Charge Time, Half-Cost Perk, Range, Target Type.

### Stats
- **When:** Modifies stats (weight, value, etc.) of items and other objects.
- **Records:** Game-specific; see per-game Stats sections. Not for FO4.

### Text
- **When:** Modifies long-form text (book text, descriptions of armor/spells/weapons, etc.).
- **Records:** Game-specific; see per-game Text sections. Not for FO4.

## Oblivion & Nehrim: At Fate's Edge

### Actors.ACBS (Oblivion specifics)
- **Records:** (ACBS) Configuration. CREA flags: Biped, Essential, Weapon & Shield, Respawn, Swims, Flies, Walks, PC Level Offset, No Low level Processing, No Blood Spray/Decal, No Head, No Right/Left Arm, No Combat in Water, No Shadow, No Corpse Check. NPC_ flags: Female, Essential, Respawn, Auto-Calc Stats, PC Level Offset, No Low Level Processing, No Rumors, Summonable, No Persuasion, Can Corpse Check. Base Spell Points, Fatigue, Barter Gold, Level (Offset), Calc Min, Calc Max. Level (Offset) and Flags\PC Level Offset are linked.

### Actors.AIData (Oblivion specifics)
- **Records:** (AIDT): Aggression, Confidence, Energy Level, Responsibility, Buys/Sells and Services, Teaches, Maximum Training Level.

### Actors.Stats (Oblivion specifics)
- **Records:** CREA (DATA): Agility, Attack, Combat Skill, Damage, Endurance, Health, Intelligence, Luck, Magic Skill, Personality, Soul, Speed, Stealth Skill, Strength, Willpower. NPC_ (DATA): Attributes (Agility/Endurance/Intelligence/Luck/Personality/Speed/Strength/Willpower), Health, Skills (Acrobatics, Alchemy, Alteration, Armorer, Athletics, Blade, Block, Blunt, Conjuration, Destruction, Hand to Hand, Heavy Armor, Illusion, Light Armor, Marksman, Mercantile, Mysticism, Restoration, Security, Sneak, Speechcraft).

### Graphics (Oblivion)
- **Records:** ACTI (MODL); ALCH/AMMO/APPA (ICON, MODL); ARMO/CLOT (BMDT, Male Biped Model, Male World Model, ICON Male, Female Biped Model, Female World Model, ICO2 Female); BOOK (ICON, MODL); BSGN/CLAS (ICON); CONT (MODL); CREA (MODL, NIFZ); DOOR (MODL); EFSH (ICON Fill Texture, ICO2 Particle Shader, DATA Flags, Membrane Shader, Fill/Texture Effect, Edge Effect, Particle Shader, Color Key); EYES (ICON); FLOR/FURN/GRAS (MODL); HAIR (ICON, MODL); INGR/KEYM (ICON, MODL); LIGH (ICON, MODL, DATA Radius/Color/Flags/Falloff/FOV, FNAM Fade); LSCR/LTEX (ICON); MGEF (ICON, MODL, DATA Light/Effect Shader/Enchant Effect); MISC (ICON, MODL); QUST/REGN (ICON); SGST (ICON, MODL); SKIL (ICON); SLGM (ICON, MODL); STAT (MODL); TREE (ICON, MODL); WEAP (ICON, MODL).

### Names (Oblivion)
- **Records:** (FULL) in ACTI, ALCH, AMMO, APPA, ARMO, BOOK, BSGN, CLAS, CLOT, CONT, CREA, DOOR, ENCH, EYES, FACT, FLOR, HAIR, INGR, KEYM, LIGH, MGEF, MISC, NPC_, QUST, RACE, SGST, SLGM, SPEL, WEAP.

### Roads
- **When:** Modifies road records.
- **Records:** (ROAD) child record of (WRLD).

### R.Attributes-F / R.Attributes-M
- **Records:** RACE (ATTR) Female/Male Strength, Intelligence, Willpower, Agility, Speed, Endurance, Personality, Luck.

### R.Eyes (Oblivion)
- **Records:** RACE (ENAM) Eyes; Face Data Part: Left Eye / Right Eye — (MODL), (MODB), (ICON).

### R.Head (Oblivion)
- **Records:** RACE Face Data Part: Head — (MODL), (MODB), (ICON).

### R.Mouth (Oblivion)
- **Records:** RACE Face Data Part: Mouth, Tongue — (MODL), (MODB), (ICON).

### R.Teeth (Oblivion)
- **Records:** RACE Face Data Part: Teeth (Lower), Teeth (Upper) — (MODL), (MODB), (ICON).

### Scripts (Oblivion)
- **Records:** (SCRI) Script in ACTI, ALCH, APPA, ARMO, BOOK, CLOT, CONT, CREA, DOOR, FLOR, FURN, INGR, KEYM, LIGH, LVLC, MISC, NPC_, QUST, SGST, SLGM, WEAP.

### Sound (Oblivion)
- **Records:** ACTI (SNAM); CONT (SNAM Open, QNAM Close); CREA (WNAM Foot Weight, CSCR Inherits Sounds, Sound Types); DOOR (SNAM Open, ANAM Close, BNAM Loop); LIGH (SNAM); MGEF (DATA Casting/Bolt/Hit/Area Sound); SOUN (FNAM, SNDX); WATR (SNAM); WTHR (SNAM).

### Stats (Oblivion)
- **Records:** ALCH (EDID, DATA Weight, ENIT Value); AMMO (EDID, ANAM Enchantment Points, DATA Speed/Value/Weight/Damage); APPA (EDID, DATA Value/Weight/Quality); ARMO (EDID, DATA Strength/Value/Health/Weight); BOOK (EDID, ANAM, DATA Value/Weight); CLOT (EDID, ANAM, DATA Value/Weight); EYES (EDID, DATA Flags); HAIR (EDID, DATA Flags); INGR (EDID, DATA Weight, ENIT Value); KEYM (EDID, DATA Value/Weight); LIGH (EDID, DATA Time/Value/Weight); MISC (EDID, DATA Value/Weight); SGST (EDID, DATA Uses/Value/Weight); WEAP (EDID, ANAM, DATA Speed/Reach/Value/Health/Weight/Damage).

### Text (Oblivion)
- **Records:** (DESC) in BOOK, BSGN, CLAS, LSCR, MGEF, SKIL. RACE uses R.Description.

## Fallout 3 & Fallout: New Vegas

### Actors.ACBS (FO3/FNV specifics)
- **Records:** (ACBS). CREA flags: Biped, Essential, Weapon & Shield, Respawn, Swims, Flies, Walks, PC Level Mult, No Low Level Processing, No Blood Spray/Decal, No Head, No Right/Left Arm, No Combat in Water, No Shadow, No VATS Melee, Allow PC Dialogue, Can't Open Doors, Immobile, Tilt Front/Back, Tilt Left/Right, No Knockdowns, Not Pushable, Allow Pickpocket, Is Ghost, No Rotating to Head-Track, Invulnerable. NPC_ flags: Essential, Female, Is CharGen Face Preset, Respawn, Auto-Calc Stats, PC Level Mult, No Low Level Processing, No Blood Spray/Decal, No VATS Melee, Can Be All Races, Autocalc Service [FNV], No Knockdowns, Not Pushable, No Rotating to Head-Track. Fatigue, Barter Gold, Level, Calc Min, Calc Max, Speed Multiplier, Karma (Alignment), Disposition Base. Level and Flags\PC Level Mult are linked.

### Actors.AIData (FO3/FNV specifics)
- **Records:** (AIDT): Aggression, Confidence, Energy Level, Responsibility, Mood, Buys/Sells and Services, Teaches, Maximum Training Level, Assistance, Aggro Radius Behavior, Aggro Radius.

### Actors.Stats (FO3/FNV specifics)
- **Records:** CREA (DATA): Attributes (Agility/Charisma/Endurance/Intelligence/Luck/Perception/Strength), Combat Skill, Damage, Health, Magic Skill, Stealth Skill. NPC_ (DATA): Attributes (same seven), Base Health; (DNAM) Skills (Values & Offsets): Barter, Big Guns, Energy Weapons, Explosives, Lockpick, Medicine, Melee Weapons, Repair, Science, Small Guns, Sneak, Speech, Throwing (Unused), Unarmed.

### Destructible (FO3/FNV)
- **Records:** (DEST, DSTD, DMDL, DMDT, DSTF) in ACTI, ALCH, AMMO, ARMO, BOOK, CHIP [FNV], CONT, CREA, DOOR, FURN, IMOD [FNV], KEYM, LIGH, MISC, MSTT, NPC_, PROJ, TACT, TERM, WEAP.

### Graphics (FO3/FNV)
- **Records:** ACTI (MODL); ALCH/AMMO (MODL, ICON, MICO); ARMA/ARMO (MODL Male Biped, MOD2 Male World, ICON Male, MICO Male Small, MOD3 Female Biped, MOD4 Female World, ICO2 Female, MIC2 Female Small, DNAM Modulates Voice, BMDT Biped Flags); AVIF (ICON, MICO); BOOK (MODL, ICON, MICO); BPTD (MODL); CCRD [FNV] (MODL, ICON, MICO, TX00, TX01); CHAL (ICON, MICO); CHIP [FNV] (MODL, ICON, MICO); CLAS (ICON); CMNY [FNV] (MODL, ICON, MICO); COBJ (ICON, MICO, MODL); CONT (MODL); CREA (MODL, NIFZ, NIFT); CSNO [FNV] (MODL Chip Models, MOD2 Slot, MOD3 Blackjack, MODT Extra Blackjack, MOD4 Roulette, ICON Slot Reel Textures, ICO2 Blackjack Decks); DOOR (MODL); EFSH (ICO2, ICON, NAM7, DATA All); EXPL (MODL, MNAM Image Space Modifier, DATA Light/Impact DataSet, INAM Placed Impact Object); EYES (ICON); FURN/GRAS (MODL); HAIR (MODL, ICON); HDPT (MODL); IMOD [FNV] (MODL, ICON, MICO); INGR (MODL, ICON); IPCT (MODL, DATA Effect Duration/Orientation/Angle Threshold/Placement Radius/Flags, DODT Decal All, DNAM Texture Set); IPDS (DATA Impacts All); KEYM (MODL, ICON, MICO); LIGH (MODL, ICON, DATA Radius/Color/Flags/Falloff/FOV, FNAM Fade); LSCR (ICON); MGEF (ICON, MODL, DATA Light/Effect Shader/Object Display Shader); MICN (ICON, MICO); MISC (MODL, ICON, MICO); MSTT (MODL); NOTE (ICON, MICO, MODL, XNAM Texture); PERK (ICON, MICO); PROJ (MODL, DATA Light/Muzzle Flash Light/Explosion/Muzzle Flash Duration/Fade Duration, NAM1 Muzzle Flash Model); PWAT (MODL); REPU [FNV] (MODL, ICON, MICO); STAT (MODL); TACT/TERM (MODL); TREE (ICON, MODL); TXST (TX00–TX05, DODT Decal All, DNAM Flags); WEAP (MODL, ICON, MICO, MOD2 Shell Casing, MOD3 Scope, EFSD Scope Effect, MOD4 World, MWD1–MWD7 Model With Mods [FNV], INAM Impact Dataset, WNAM First Person, WNM1–WNM7 First Person With Mods [FNV], DNAM Animation Type/Grip Animation/Reload Animation).

### Names (FO3/FNV)
- **Records:** (FULL) in ACTI, ALCH, AMMO, ARMO, AVIF, BOOK, CCRD [FNV], CHAL [FNV], CHIP [FNV], CLAS, CMNY [FNV], COBJ, CONT, CREA, CSNO [FNV], DOOR, EYES, FACT, HAIR, IMOD [FNV], INGR, KEYM, LIGH, MESG, MGEF, MISC, NOTE, NPC_, PERK, QUST, RACE, RCCT [FNV], RCPE [FNV], REPU [FNV], SPEL, TACT, TERM, WEAP.

### ObjectBounds (FO3/FNV)
- **Records:** (OBND) in ACTI, ADDN, ALCH, AMMO, ARMA, ARMO, ASPC, BOOK, CCRD [FNV], CHIP [FNV], CMNY [FNV], COBJ, CONT, CREA, DOOR, EXPL, FURN, GRAS, IDLM, IMOD [FNV], INGR, KEYM, LIGH, LVLC, LVLI, LVLN, MISC, MSTT, NOTE, NPC_, PROJ, PWAT, SCOL, SOUN, STAT, TACT, TERM, TREE, TXST, WEAP.

### R.Eyes (FO3/FNV)
- **Records:** RACE (ENAM) Eyes; Face Data Part: Left Eye / Right Eye (Female, Male) — (MODL), (MODB), (ICON).

### R.Head (FO3/FNV)
- **Records:** RACE Face Data Part: Head (Female, Male) — (MODL), (MODB), (ICON).

### R.Mouth (FO3/FNV)
- **Records:** RACE Face Data Part: Mouth / Tongue (Female, Male) — (MODL), (MODB), (ICON).

### R.Teeth (FO3/FNV)
- **Records:** RACE Face Data Part: Teeth (Lower/Upper, Female/Male) — (MODL), (MODB), (ICON).

### Scripts (FO3/FNV)
- **Records:** (SCRI) Script in ACTI, ALCH, AMMO [FNV], ARMO, BOOK, COBJ, CCRD [FNV], CHAL [FNV], CONT, CREA, DOOR, FURN, IMOD [FNV], INGR, KEYM, LIGH, MISC, NPC_, QUST, TACT, TERM, WEAP.

### Sound (FO3/FNV)
- **Records:** ACTI (SNAM Looping, VNAM Activation); ADDN (SNAM); ALCH (ZNAM Drop, YNAM Pick Up, ENIT Consume); ARMO (YNAM, ZNAM); ASPC (SNAM Looping [FO3], SNAM Dawn/Afternoon/Dusk/Night/Walla [FNV], RDAT Region Sound, ANAM Environment Type); COBJ (YNAM, ZNAM); CONT (SNAM Open, QNAM Close, RNAM Random/Looping [FNV]); CREA (WNAM Foot Weight, CSCR Inherits, CSDT Type, CSDI Sound, CSDC Chance); DOOR (SNAM Open, ANAM Close, BNAM Loop); EXPL (DATA Sound Level/Sound 1/Sound 2); IPCT (DATA Sound Level, SNAM Sound 1, NAM1 Sound 2); KEYM (Pick Up, Drop, RNAM [FNV]); LIGH (SNAM); MGEF (DATA Effect/Bolt/Hit/Area Sound); MISC (YNAM, ZNAM, RNAM [FNV]); NOTE (YNAM, ZNAM, SNAM Sound/NPC); PROJ (DATA Sound/Countdown/Disable, VNAM Sound Level); SOUN (FNAM, SNDD); STAT (BRUS Passthrough [FNV], RNAM [FNV]); TACT/TERM (SNAM); WATR (SNAM); WEAP (YNAM, ZNAM, SNAM Shoot 3D, SNAM Shoot Dist [FNV], XNAM Shoot 2D, NAM7 Shoot 3D Looping, TNAM Melee Swing/No Ammo, NAM6 Block, UNAM Idle, NAM9 Equip, NAM8 Unequip, WMS1/WMS2 Mod 1 Sounds [FNV], VNAM Sound Level); WTHR (SNAM Sound: Sound, Type).

### Stats (FO3/FNV)
- **Records:** ALCH (EDID, DATA Weight, ENIT Value); AMMO (EDID, DATA Speed/Value/Clip Rounds, DAT2 Proj. per Shot/Weight [FNV]); ARMA/ARMO (EDID, DATA Value/Max Condition/Weight, DNAM DR/DT [FNV]); BOOK (EDID, DATA Value/Weight); EYES/HAIR/HDPT (EDID, DATA Flags); INGR (DATA Weight, ENIT Value); KEYM (EDID, DATA Value/Weight); LIGH (EDID, DATA Time/Value/Weight); MISC (EDID, DATA Value/Weight); WEAP (EDID, DATA Value/Health/Weight/Base Damage/Clip Size, DNAM Animation/Reach/Ammo Use/Spread/Sight FOV/VATS/Projectile Count/Range/Fire Rate/AP/Rumble/Damage Mult/Reload Time/Jam Time/Strength Req [FNV]/Regen Rate [FNV]/Kill Impulse [FNV]/Skill Req [FNV], CRDT Critical Damage/Crit % Mult, VATS Skill/Dam. Mult/AP [FNV]).

### Text (FO3/FNV)
- **Records:** ACTI (XATO Activation Prompt [FNV]); AMMO (ONAM Short Name, QNAM Abbreviation [FNV]); AVIF (DESC, ANAM Short Name); BOOK (DESC Book Text); CHAL [FNV] (DESC); CLAS (DESC); IMOD [FNV] (DESC); LSCR (DESC); MESG (DESC); MGEF (DESC); NOTE (TNAM Note Text); PERK (DESC); TERM (DESC). RACE uses R.Description.

### WeaponMods (FNV only)
- **When:** Modifies weapon modifications. Shares subrecords with Graphics and Sound for backwards compatibility; prefer WeaponMods.
- **Records:** WEAP (MWD1–MWD7) Model With Mods; (WNM1–WNM7) First Person With Mods; (WMI1/WMI2/WMI3) Weapon Mods; (WMS1/WMS2) Mod 1 Sounds; (DNAM) Flags 2: Scope From Mod, Effect Mod 1/2/3, Value A/B Mod 1/2/3, Reload Animation Mod; (VATS) Mod Required.

## Skyrim, Enderal: Forgotten Stories & Skyrim: Special Edition

### Actors.ACBS (Skyrim/Enderal/SSE specifics)
- **Records:** (ACBS) Flags (Female, Essential, Is CharGen Face Preset, Respawn, Auto-Calc Stats, Unique, Doesn't Affect Stealth Meter, PC Level Mult, Protected, Summonable, Doesn't Bleed, Bleedout Override, Opposite Gender Animations, Simple Actor, Looped Script, Looped Audio, Is Ghost, Invulnerable); Magicka Offset, Stamina Offset, Level, Calc Min Level, Calc Max Level, Speed Multiplier, Disposition Base, Health Offset, Bleedout Override. Level and Flags\PC Level Mult are linked.

### Actors.AIData (Skyrim/Enderal/SSE specifics)
- **Records:** (AIDT): Aggression, Confidence, Energy Level, Morality, Mood, Assistance, Aggro (Radius Behavior, Warn, Warn/Attack, Attack).

### Actors.Stats (Skyrim/Enderal/SSE specifics)
- **Records:** NPC_ (DNAM): Health, Magicka, Skills Values & Offsets (Alchemy, Alteration, Block, Conjuration, Destruction, Enchanting, HeavyArmor, Illusion, LightArmor, Lockpicking, Marksman, OneHanded, Pickpocket, Restoration, Smithing, Sneak, Speechcraft, TwoHanded), Stamina.

### Destructible (Skyrim)
- **Records:** (DEST, DSTD, DMDL, DMDT, DMDS, DSTF) in ACTI, ALCH, AMMO, APPA, ARMO, BOOK, CONT, DOOR, FLOR, FURN, KEYM, LIGH, MISC, MSTT, NPC_, PROJ, SCRL, SLGM, TACT, WEAP.

### Graphics (Skyrim)
- **Records:** ACTI (MODL); ALCH/AMMO/APPA (ICON, MODL); ARMA (MOD2 Male World, MOD3 Female World, MOD4 Male 1st Person, MOD5 Female 1st Person, BODT/BOD2 First Person Flags); ARMO (MOD2 Male World, ICON Male, MOD3 Female World, ICO2 Female, MODL Armature, BODT/BOD2); AVIF (ICON); BOOK (ICON, MODL, INAM Inventory Art); CLAS (ICON); CONT/DOOR (MODL); EFSH (ICON Fill, ICO2 Particle, NAM7 Holes, NAM8 Membrane Palette, NAM9 Particle Palette, DATA All); EXPL (MODL, MNAM Image Space Modifier, DATA Light/Impact Dataset); FLOR/FURN/GRAS (MODL); HDPT (MODL, TNAM Texture Set, CNAM Color); INGR (ICON, MODL); IPCT (MODL, DATA Effect/Impact Result, DODT, DNAM Texture Set); KEYM (ICON, MODL); LIGH (ICON, MODL, DATA Radius/Color/Flags/Falloff/FOV/Near Clip/Flicker, FNAM Fade); LSCR (NNAM Loading Screen NIF, SNAM Initial Scale, RNAM Rotation, ONAM Rotation Offset, XNAM Initial Translation, MOD2 Camera Path); MGEF (MDOB Menu Display Object, DATA Casting Light/Hit Shader/Enchant Shader/Projectile/Explosion/Casting Art/Hit Effect Art/Impact Data/Dual Casting Art+Scale/Enchant Art/Hit Visuals/Enchant Visuals/Image Space Modifier); MISC (ICON, MODL); PERK (ICON); PROJ (MODL, DATA Light/Muzzle Flash Light/Explosion/Muzzle Flash Duration/Fade Duration/Decal Data, NAM1 Muzzle Flash Model); SCRL (MDOB); SLGM (ICON, MODL); SPEL (MDOB); STAT (MODL); TREE (ICON, MODL); TXST (TX00 Diffuse, TX01 Normal/Gloss, TX02 Environment Mask/Subsurface, TX03 Glow/Detail, TX04 Height, TX05 Environment, TX06 Multilayer, TX07 Backlight Mask/Specular, DODT, DNAM Flags); WEAP (MODL, MOD3 Has Scope, EFSD Scope Effect, ICON, WNAM 1st Person Model); WTHR (DALC Directional Ambient Lighting Colors).

### Keywords (Skyrim)
- **Records:** (KWDA/KSIZ) in ACTI, ALCH, AMMO, ARMO, BOOK, FLOR, FURN, INGR, KEYM, LCTN, MGEF, MISC, NPC_, RACE, SCRL, SLGM, SPEL, TACT, WEAP.

### Names (Skyrim)
- **Records:** (FULL) in ACTI, ALCH, AMMO, APPA, ARMO, AVIF, BOOK, CLAS, CLFM, CONT, DOOR, ENCH, EXPL, EYES, FACT, FLOR, FURN, HAZD, HDPT, INGR, KEYM, LCTN, LIGH, MESG, MGEF, MISC, MSTT, NPC_, PERK, QUST, RACE, SCRL, SHOU, SLGM, SNCT, SPEL, TACT, TREE, WATR, WEAP, WOOP.

### ObjectBounds (Skyrim)
- **Records:** (OBND) in ACTI, ADDN, ALCH, AMMO, APPA, ARMO, ARTO, ASPC, BOOK, CONT, DOOR, DUAL, ENCH, EXPL, FLOR, FURN, GRAS, HAZD, IDLM, INGR, KEYM, LIGH, LVLI, LVLN, LVSP, MISC, MSTT, NPC_, PROJ, SCRL, SLGM, SOUN, SPEL, STAT, TACT, TREE, TXST, WEAP.

### R.Stats (Skyrim)
- **Records:** RACE (DATA) Starting Health/Magicka/Stamina, Base Carry Weight, Health Regen, Magicka Regen, Stamina Regen, Unarmed Damage, Unarmed Reach.

### Sound (Skyrim)
- **Records:** ACTI (SNAM Looping, VNAM Activation); ADDN (SNAM); ALCH (YNAM, ZNAM, ENIT Consume); AMMO/APPA (YNAM, ZNAM); ARMA (SNDD Footstep); ARMO (YNAM, ZNAM); ASPC (SNAM Ambient, RDAT Region Sound, BNAM Environment Type); BOOK (YNAM, ZNAM); CONT (SNAM Open, QNAM Close); DOOR (SNAM Open, ANAM Close, BNAM Loop); EFSH (DATA Ambient Sound); EXPL (DATA Sound 1/Sound 2/Sound Level); FLOR (SNAM); HAZD (DATA Sound); INGR (YNAM, ZNAM); IPCT (DATA Sound Level, SNAM Sound 1, NAM1 Sound 2); KEYM (YNAM, ZNAM); LIGH (SNAM); MGEF (DATA Casting Sound Level, SNDD Sounds); MISC (YNAM, ZNAM); MSTT (SNAM Looping); PROJ (DATA Sound/Countdown/Disable, VNAM Sound Level); SCRL/SLGM (YNAM, ZNAM); SNCT (PNAM Parent, VNAM Static Volume Multiplier); SNDR (GNAM Category, SNAM Alternate Sound For, ANAM Sounds, ONAM Output Model, LNAM/BNAM Values); SOPM (NAM1 Reverb Send %, MNAM Type, ONAM Output Values, ANAM Attenuation Curve); SOUN (SDSC Sound Descriptor); TACT (SNAM Looping); TREE (SNAM Harvest); WATR (SNAM Open); WEAP (YNAM, ZNAM, SNAM Attack, XNAM Attack 2D, NAM7 Attack Loop, TNAM Attack Fail, UNAM Idle, NAM9 Equip, NAM8 Unequip, VNAM Detection Sound Level); WTHR (SNAM Sounds).

### Stats (Skyrim)
- **Records:** ALCH (EDID, DATA Weight, ENIT Value); AMMO (EDID, DATA Damage/Value/Weight [SSE]); APPA (EDID, DATA Value/Weight); ARMO (EDID, DATA Value/Weight, DNAM Armor Rating); BOOK (EDID, DATA Value/Weight); INGR (EDID, DATA Value/Weight); EYES/HDPT (EDID, DATA Flags); KEYM (EDID, DATA Value/Weight); LIGH (EDID, DATA Time/Value/Weight); MISC (EDID, DATA Value/Weight); SLGM (EDID, DATA Value/Weight); WEAP (EDID, EAMT Enchantment Amount, DATA Value/Weight/Damage, DNAM Speed/Reach/Stagger, CRTD Critical Damage/Multiplier).

### Text (Skyrim)
- **Records:** ACTI (RNAM Activate Text Override); ALCH (DESC); AMMO (DESC, ONAM Short Name); APPA (DESC); ARMO (DESC); ASTP (MPRT/FPRT/MCHT/FCHT Parent/Child Titles); AVIF (DESC, ANAM Abbreviation); BOOK (DESC Book Text, CNAM Description); CLAS (DESC); COLL (DESC); FLOR (RNAM Activate Text Override); LSCR (DESC); MESG (DESC); MGEF (DNAM Magic Item Description); NPC_ (SHRT Short Name); PERK (DESC); QUST (NNAM Description); SCRL (DESC); SHOU (DESC); SPEL (DESC); WEAP (DESC); WOOP (TNAM Translation). RACE uses R.Description.

## Fallout 4

### Actors.ACBS (FO4 specifics)
- **Records:** (ACBS) Flags (Female, Essential, Is CharGen Face Preset, Respawn, Auto-Calc Stats, Unique, Doesn't Affect Stealth Meter, PC Level Mult, Protected, Summonable, Doesn't Bleed, Bleedout Override, Opposite Gender Anims, Simple Actor, No Activation/Hellos, Diffuse Alpha Test, Is Ghost, Invulnerable); XP Value Offset, Level, Calc Min Level, Calc Max Level, Disposition Base, Bleedout Override. Level and Flags\PC Level Mult are linked.

### Actors.AIData (FO4 specifics)
- **Records:** (AIDT): Aggression, Confidence, Energy Level, Morality, Mood, Assistance, Aggro (Radius Behavior, Warn, Warn/Attack, Attack).

### Actors.Stats (FO4 specifics)
- **Records:** NPC_ (PRPS) Properties (health, SPECIAL, action points, etc.).

### Destructible (FO4)
- **Records:** (DEST, DAMC, DSTA, DSTD, DMDL, DMDT, DMDC, DMDS, DSTF) in ACTI, ALCH, AMMO, ARMO, BOOK, CONT, DOOR, FLOR, FURN, INGR, KEYM, LIGH, MISC, MSTT, NPC_, PROJ.

### Keywords (FO4)
- **Records:** (KWDA/KSIZ) in ACTI, ALCH, AMMO, ARMO, ARTO, BOOK, CONT, DOOR, FLOR, FURN, IDLM, INGR, KEYM, LCTN, LIGH, MGEF, MISC, MSTT, NPC_, SPEL.

### Names (FO4)
- **Records:** (FULL) in AACT, ACTI, ALCH, AMMO, ARMO, AVIF, BOOK, CLAS, CLFM, CMPO, CONT, DOOR, ENCH, EXPL, FACT, FLOR, FLST, FURN, HAZD, HDPT, INGR, KEYM, KYWD, LIGH, MESG, MGEF, MISC, MSTT, NOTE, NPC_, OMOD, PERK, PROJ, SCOL, SNCT, SPEL, STAT.

### ObjectBounds (FO4)
- **Records:** (OBND) in ACTI, ADDN, ALCH, AMMO, ARMO, ARTO, ASPC, BNDS, BOOK, CMPO, CONT, DOOR, ENCH, EXPL, FLOR, FURN, GRAS, HAZD, IDLM, INGR, KEYM, LIGH, LVLI, LVLN, LVSP, MISC, MSTT, NOTE, NPC_, PKIN, PROJ, SCOL, SOUN, SPEL, STAT.
